# Chunky Configuration
# https://github.com/pop4959/Chunky/wiki/Configuration
version: 1
language: en
continue-on-restart: false
tasks:
  AnGame:
    cancelled: true
    radius: 1000
    x-center: 0
    z-center: 0
    iterator: concentric
    shape: square
    count: 16079
    time: 262030
